// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: n5Fhkbw8v9iAr45cMpgyB5
// Component: 7juZWqVc7aLc
import * as React from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  initializeCodeComponentStates,
  useCurrentUser,
  useDollarState
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv
} from "@plasmicapp/react-web/lib/host";
import { usePlasmicDataOp } from "@plasmicapp/react-web/lib/data-sources";
import PageLayout from "../../PageLayout"; // plasmic-import: LntSjwsq1IGJ/component
import { AntdInput } from "@plasmicpkgs/antd5/skinny/registerInput";
import { inputHelpers as AntdInput_Helpers } from "@plasmicpkgs/antd5/skinny/registerInput";
import { RichTable } from "@plasmicpkgs/plasmic-rich-components/skinny/rich-table";
import { tableHelpers as RichTable_Helpers } from "@plasmicpkgs/plasmic-rich-components/skinny/rich-table";
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: n5Fhkbw8v9iAr45cMpgyB5/projectcss
import sty from "./PlasmicProvincesPage.module.css"; // plasmic-import: 7juZWqVc7aLc/css

createPlasmicElementProxy;

export const PlasmicProvincesPage__VariantProps = new Array();

export const PlasmicProvincesPage__ArgProps = new Array();

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicProvincesPage__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = useCurrentUser?.() || {};
  let [$queries, setDollarQueries] = React.useState({});
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "provincesTable.selectedRowKey",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,
        onMutate: generateOnMutateForSpec("selectedRowKey", RichTable_Helpers)
      },
      {
        path: "provincesTable.selectedRow",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,
        onMutate: generateOnMutateForSpec("selectedRow", RichTable_Helpers)
      },
      {
        path: "provincesTable.selectedRows",
        type: "private",
        variableType: "array",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,
        onMutate: generateOnMutateForSpec("selectedRows", RichTable_Helpers)
      },
      {
        path: "provincesTable.selectedRowKeys",
        type: "private",
        variableType: "array",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,
        onMutate: generateOnMutateForSpec("selectedRowKeys", RichTable_Helpers)
      },
      {
        path: "pageLayout.baseUrl",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "provincesSearch.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,
        onMutate: generateOnMutateForSpec("value", AntdInput_Helpers)
      }
    ],

    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: $queries,
    $refs
  });
  const new$Queries = {
    provincesQuery: usePlasmicDataOp(() => {
      return {
        sourceId: "9qjX5dCe3WEpTMCp4MyMNP",
        opId: "8fa0a44f-6ac5-406d-8e3a-1daa5dda1c08",
        userArgs: {
          params: [$state.provincesSearch.value]
        },
        cacheKey: `plasmic.$.8fa0a44f-6ac5-406d-8e3a-1daa5dda1c08.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    })
  };
  if (Object.keys(new$Queries).some(k => new$Queries[k] !== $queries[k])) {
    setDollarQueries(new$Queries);
    $queries = new$Queries;
  }
  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicProvincesPage.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicProvincesPage.pageMetadata.title}
        />

        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicProvincesPage.pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"provinces"}
          data-plasmic-override={overrides.provinces}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            plasmic_plasmic_rich_components_css.plasmic_tokens,
            sty.provinces
          )}
        >
          <PageLayout
            data-plasmic-name={"pageLayout"}
            data-plasmic-override={overrides.pageLayout}
            className={classNames("__wab_instance", sty.pageLayout)}
            onBaseUrlChange={generateStateOnChangeProp($state, [
              "pageLayout",
              "baseUrl"
            ])}
          >
            <DataCtxReader__>
              {$ctx => (
                <section
                  data-plasmic-name={"section"}
                  data-plasmic-override={overrides.section}
                  className={classNames(projectcss.all, sty.section)}
                >
                  <h1
                    data-plasmic-name={"h1"}
                    data-plasmic-override={overrides.h1}
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1
                    )}
                  >
                    {"Provinces"}
                  </h1>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__nWyqZ
                    )}
                  >
                    {"Here are list of provinces."}
                  </div>
                  {(() => {
                    const child$Props = {
                      addonAfter: null,
                      addonBefore: (
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__ukKjc
                          )}
                        >
                          {"Search.."}
                        </div>
                      ),

                      allowClear: true,
                      autoFocus: true,
                      bordered: true,
                      className: classNames(
                        "__wab_instance",
                        sty.provincesSearch
                      ),
                      onChange: async (...eventArgs) => {
                        generateStateOnChangePropForCodeComponents(
                          $state,
                          "value",
                          ["provincesSearch", "value"],
                          AntdInput_Helpers
                        ).apply(null, eventArgs);
                        (async event => {
                          const $steps = {};
                        }).apply(null, eventArgs);
                      },
                      type: "text",
                      value: generateStateValueProp($state, [
                        "provincesSearch",
                        "value"
                      ])
                    };
                    initializeCodeComponentStates(
                      $state,
                      [
                        {
                          name: "value",
                          plasmicStateName: "provincesSearch.value"
                        }
                      ],

                      [],
                      AntdInput_Helpers ?? {},
                      child$Props
                    );
                    return (
                      <AntdInput
                        data-plasmic-name={"provincesSearch"}
                        data-plasmic-override={overrides.provincesSearch}
                        {...child$Props}
                      />
                    );
                  })()}
                  {(() => {
                    const child$Props = {
                      canSelectRows: "click",
                      className: classNames(
                        "__wab_instance",
                        sty.provincesTable
                      ),
                      data: (() => {
                        try {
                          return $queries.provincesQuery.data.response
                            .provinces;
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return undefined;
                          }
                          throw e;
                        }
                      })(),
                      defaultSize: "small",
                      fields: (() => {
                        const __composite = [
                          {
                            key: "id",
                            fieldId: "id",
                            isHidden: null,
                            title: null
                          },
                          { key: "name", fieldId: "name", title: null },
                          { key: "slug", fieldId: "slug", title: null },
                          {
                            key: "createdAt",
                            fieldId: "createdAt",
                            isHidden: null
                          },
                          {
                            key: "updatedAt",
                            fieldId: "updatedAt",
                            isHidden: null
                          }
                        ];

                        __composite["0"]["isHidden"] = true;
                        __composite["0"]["title"] = "ID";
                        __composite["1"]["title"] = "Name";
                        __composite["2"]["title"] = "Slug";
                        __composite["3"]["isHidden"] = true;
                        __composite["4"]["isHidden"] = true;
                        return __composite;
                      })(),
                      hideColumnPicker: true,
                      hideDensity: true,
                      hideSearch: true,
                      onRowClick: async (rowKey, row, event) => {
                        const $steps = {};
                      },
                      onRowSelectionChanged: async (...eventArgs) => {
                        generateStateOnChangePropForCodeComponents(
                          $state,
                          "selectedRowKey",
                          ["provincesTable", "selectedRowKey"],
                          RichTable_Helpers
                        ).apply(null, eventArgs);
                        generateStateOnChangePropForCodeComponents(
                          $state,
                          "selectedRow",
                          ["provincesTable", "selectedRow"],
                          RichTable_Helpers
                        ).apply(null, eventArgs);
                        generateStateOnChangePropForCodeComponents(
                          $state,
                          "selectedRows",
                          ["provincesTable", "selectedRows"],
                          RichTable_Helpers
                        ).apply(null, eventArgs);
                        generateStateOnChangePropForCodeComponents(
                          $state,
                          "selectedRowKeys",
                          ["provincesTable", "selectedRowKeys"],
                          RichTable_Helpers
                        ).apply(null, eventArgs);
                      },
                      pageSize: 100,
                      rowKey: ``,
                      scopeClassName: sty["provincesTable__instance"],
                      selectedRowKey: generateStateValueProp($state, [
                        "provincesTable",
                        "selectedRowKey"
                      ]),
                      selectedRowKeys: generateStateValueProp($state, [
                        "provincesTable",
                        "selectedRowKeys"
                      ]),
                      themeResetClassName: classNames(
                        projectcss.root_reset,
                        projectcss.root_reset_tags,
                        projectcss.plasmic_default_styles,
                        projectcss.plasmic_mixins,
                        projectcss.plasmic_tokens,
                        plasmic_antd_5_hostless_css.plasmic_tokens,
                        plasmic_plasmic_rich_components_css.plasmic_tokens
                      )
                    };
                    initializeCodeComponentStates(
                      $state,
                      [
                        {
                          name: "selectedRowKey",
                          plasmicStateName: "provincesTable.selectedRowKey"
                        },
                        {
                          name: "selectedRow",
                          plasmicStateName: "provincesTable.selectedRow"
                        },
                        {
                          name: "selectedRows",
                          plasmicStateName: "provincesTable.selectedRows"
                        },
                        {
                          name: "selectedRowKeys",
                          plasmicStateName: "provincesTable.selectedRowKeys"
                        }
                      ],

                      [],
                      RichTable_Helpers ?? {},
                      child$Props
                    );
                    return (
                      <RichTable
                        data-plasmic-name={"provincesTable"}
                        data-plasmic-override={overrides.provincesTable}
                        {...child$Props}
                      />
                    );
                  })()}
                </section>
              )}
            </DataCtxReader__>
          </PageLayout>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  provinces: [
    "provinces",
    "pageLayout",
    "section",
    "h1",
    "provincesSearch",
    "provincesTable"
  ],

  pageLayout: [
    "pageLayout",
    "section",
    "h1",
    "provincesSearch",
    "provincesTable"
  ],

  section: ["section", "h1", "provincesSearch", "provincesTable"],
  h1: ["h1"],
  provincesSearch: ["provincesSearch"],
  provincesTable: ["provincesTable"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicProvincesPage__ArgProps,
          internalVariantPropNames: PlasmicProvincesPage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicProvincesPage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "provinces") {
    func.displayName = "PlasmicProvincesPage";
  } else {
    func.displayName = `PlasmicProvincesPage.${nodeName}`;
  }
  return func;
}

export const PlasmicProvincesPage = Object.assign(
  // Top-level PlasmicProvincesPage renders the root element
  makeNodeComponent("provinces"),
  {
    // Helper components rendering sub-elements
    pageLayout: makeNodeComponent("pageLayout"),
    section: makeNodeComponent("section"),
    h1: makeNodeComponent("h1"),
    provincesSearch: makeNodeComponent("provincesSearch"),
    provincesTable: makeNodeComponent("provincesTable"),
    // Metadata about props expected for PlasmicProvincesPage
    internalVariantProps: PlasmicProvincesPage__VariantProps,
    internalArgProps: PlasmicProvincesPage__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "Provinces",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicProvincesPage;
/* prettier-ignore-end */
